spring:
   profiles: dev
   jpa:
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
server:
   port: 8000
---
spring:
   profiles: prod
   jpa:
      hibernate:
         ddl-auto: none
         use-new-id-generator-mappings: false
server:
   port: 8080