INSERT INTO BANK_ACCOUNT (ACCOUNT_NUMBER, PIN, OPENING_BALANCE, OVERDRAFT) VALUES (123456789, '1234', 800, 200);
INSERT INTO BANK_ACCOUNT (ACCOUNT_NUMBER, PIN, OPENING_BALANCE, OVERDRAFT) VALUES (987654321, '4321', 1230, 150);

INSERT INTO ATM_MACHINE_BALANCE (BILL_DENOMINATION, NUMBER_OF_BILLS) VALUES ('50 EUROS', 10);
INSERT INTO ATM_MACHINE_BALANCE (BILL_DENOMINATION, NUMBER_OF_BILLS) VALUES ('20 EUROS', 30);
INSERT INTO ATM_MACHINE_BALANCE (BILL_DENOMINATION, NUMBER_OF_BILLS) VALUES ('10 EUROS', 30);
INSERT INTO ATM_MACHINE_BALANCE (BILL_DENOMINATION, NUMBER_OF_BILLS) VALUES ('05 EUROS', 20);