CREATE TABLE BANK_ACCOUNT(
	ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
	ACCOUNT_NUMBER NUMBER NOT NULL UNIQUE,
	PIN VARCHAR2(500) NOT NULL,
	OPENING_BALANCE NUMBER,
	OVERDRAFT NUMBER
);

CREATE TABLE ATM_MACHINE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	BILL_DENOMINATION NUMBER NOT NULL UNIQUE,
	NUMBER_OF_BILLS NUMBER NOT NULL
);

CREATE TABLE AUTHENTICATION_LOG(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ACCOUNT_NUMBER NUMBER NOT NULL,
	TOKEN VARCHAR2(200) NOT NULL,
	TOKEN_ISSUE_TIME TIMESTAMP NOT NULL,
	VALID BIT NOT NULL
);